# Generated by Django 4.1 on 2022-09-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scimol", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="favorite", new_name="mol",),
    ]
